# 3.1 넘파이 배열
- 리스트의 단점 개선
- 적은 메모리로 많은 데이터를 빠르게 처리 가능 

- 조건
    1. 모든 원소가 같은 자료형이어야한다. 
    2. 원소의 개수를 바꿀 수 없다. 

## 1차원 배열

In [2]:
import numpy as np

ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(ar)
print(type(ar))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


## 벡터화 연산
- for문 쓸 필요 없이 반복연산을 한번에 처리

In [4]:
print(ar * 2)

[ 0  2  4  6  8 10 12 14 16 18]


In [5]:
# 리스트의 경우 x2로 인식하는 것이 아니라 객체의 크기가 2배 증가한다. 
l = [1, 2, 3]
l *2

[1, 2, 3, 1, 2, 3]

In [6]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [7]:
2 * a + b

array([12, 24, 36])

In [8]:
a == 2

array([False,  True, False])

In [9]:
b > 10

array([False,  True,  True])

In [10]:
(a == 2) & (b > 10)

array([False,  True, False])

## 2차원 배열 

In [11]:
c = np.array([[0, 1, 2], [3, 4, 5]])  # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
# 행의 갯수
len(c)

2

In [13]:
# 열의 갯수
len(c[0])

3

## 3차원 배열

![nn](ndim3.JPG)


![nn](3dim.jpg)

- ndim = 3인데, shape은 (2, 3, 4)인 경우 
- 3차원인 것은 맞는데, 3차원에서 깊이가 2라서 그런게 아닌가 싶다. 

In [14]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
               
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array

In [15]:
len(d), len(d[0]), len(d[0][0]) # 깊이, 행, 열 

(2, 3, 4)

In [19]:
print(d.ndim) # 3차원 
print(d.shape)

3
(2, 3, 4)


In [23]:
arr232 = np.array([[[111,112],
                    [121,122],
                    [131,132] ],
                    
                   [ [211,212],
                    [221,222],
                    [231,232] ] ] )
print(arr232.ndim)
print(arr232.shape)

3
(2, 3, 2)


In [25]:
a3 = np.array( [ [ [ 1, 2, 3 ] , 
                  [ 1, 2, 3 ] ] ,

                     [ [ 1, 2, 3 ] , 
                      [ 1, 2, 3 ] ] ,
                      
                     [ [ 1, 2, 3 ] , 
                      [ 1, 2, 3 ] ] ] )
print(a3.ndim)
print(a3.shape)

3
(3, 2, 3)


In [17]:
a = np.array([1, 2, 3])
print(a.ndim) # 1차원
print(a.shape) # 3행 

1
(3,)


In [18]:
# c = np.array([[0, 1, 2], [3, 4, 5]])
print(c.ndim) # 2차원
print(c.shape) # 2행 3열 

2
(2, 3)
