### 배열의 생성

- zeros, ones

- zeros_like, ones_like

- empty

- arange

- linspace, logspace

In [4]:
import numpy as np
a = np.zeros(5)
a


array([0., 0., 0., 0., 0.])

In [5]:

c = np.zeros((5, 2), dtype="i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [6]:
e = np.ones((2, 3, 4), dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [8]:
# c와 같은 배열의 크기를 생성하지만, 모두 1로 만들고 싶을때 
f = np.ones_like(c, dtype="f")
f

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

다차원을 1차원으로 변경

In [11]:
f.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [12]:
f.ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

차원만 1개 증가 

In [16]:
newf = f[: , np.newaxis]
print(f.ndim)
print(f.shape)
print(newf.ndim)
print(newf.shape)

2
(5, 2)
3
(5, 1, 2)


In [17]:
newf

array([[[1., 1.]],

       [[1., 1.]],

       [[1., 1.]],

       [[1., 1.]],

       [[1., 1.]]], dtype=float32)

## 배열 연결
- hstack

- vstack

- dstack

- stack

- r_

- c_

- tile

In [19]:
# hstack은 열을 늘리는 것 
a1 = np.ones((2, 3))
a2 = np.ones((2, 1))
np.hstack([a1, a2])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
# vstack은 행을 늘리는 것 
b1 = np.ones((2, 3))
b2 = np.zeros((3, 3))
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# dstack은 차원을 늘리는 것 (깊이)
c1 = np.ones((3, 4))
c2 = np.zeros((3, 4))
c12 = np.dstack([c1, c2])
print(c12.ndim)
print(c12.shape)
print(c12)

3
(3, 4, 2)
[[[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]]


In [24]:
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
## stack은 축을 지정해줄 수 있다 
c = np.stack([c1, c2]) # axis = 0 
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [28]:
print(c.shape)

(2, 3, 4)


In [29]:
c = np.stack([c1, c2], axis=1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [30]:
print(c.shape)

(3, 2, 4)


In [31]:
# _r : hstack은 배열을 좌우로 연결 
# 특수 매서드 : indexer 인덱서 
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([1, 2, 3, 4, 5, 6])

In [32]:
# c_ : 차원을 증가시킨 후 좌우로 연결 
# 1차원을 연결하면 2차원이 된다. 
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [33]:
# title은 동일한 배열은 반복연결 
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [37]:
np.tile(a, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [41]:
# 매쉬 그리드
# 2차원 그리드 포인트 생성 
x = np.arange(3)
print(x)
y = np.arange(5)
print(y)

[0 1 2]
[0 1 2 3 4]


In [40]:
X, Y = np.meshgrid(x, y)
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [42]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])